name: Build Workflow
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> ${GITHUB_ENV}

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

      - name: Install dependencies
        run: go get .

      - name: Go Build
        run: go build -v ./...

      - name: Go Unit Test
        run: go test -v -cover -covermode=atomic ./...

      - name: install swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Go Unit Test
        run: swag init

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
          #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/

      - name: tbls
        run: |
          rm .gitignore
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add docs/swagger.yaml
          git commit -m "GitHub Actions から差分を Push"; \
          git push origin HEAD:${GITHUB_REF}; \

